version: '3.1'

services:
  php1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3100:80
    volumes:
      - ./Admin:/var/www/html/
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:80
    volumes:
      - ./WebShop:/var/www/html/
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - mysql-data:/var/lib/mysql 
      #ánh xạ dữ liệu sang var/lib/mysql để phòng trường hợp mysql-data bị sập thì dữ liệu trong mysql vẫn còn

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  mysql-data: